# helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 30m

  chart:
    spec:
      chart: tailscale-operator
      version: "1.82.5"
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system

  values:
    oauth:
      clientId: ""
      clientSecret: ""

    operatorConfig:
      hostname: k3s-operator

    apiServerProxyConfig:
      mode: "true"

  valuesFrom:
    - kind: Secret
      name: operator-oauth
      valuesKey: client_id
      targetPath: oauth.clientId

    - kind: Secret
      name: operator-oauth
      valuesKey: client_secret
      targetPath: oauth.clientSecret
