apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:yhQd+QcGOWqtNdmBvJbSfaA=,iv:YHENmsFZe9FeYjJp1qmOWMXDQJtQEn1njlJYB9zMSGU=,tag:ZQer/02OnLrs/SGQWj977w==,type:str]
    client_secret: ENC[AES256_GCM,data:xzZB1FyJOUNhx6+ogvmbpEyBnB0HUZPC2Jrwq4o0MKEdWK5IIuNXAi9e/NVJSUeanhYhrjmOeYp6speDmdE1Kg==,iv:uLRPRs7QymwIcPnxOqgQGMH86cwLY6aITnjmU0ZdneU=,tag:XKVYnoHORrTIjtHkwXdDFA==,type:str]
sops:
    age:
        - recipient: age182ptu7w6gaa8xeq52p5wd493t07qducqw4husg0z6hyh97jdsf6s3y4gfn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUOWw4VDcwc2RKRnJjNElz
            MTgvMmIyZ2FIVjZsV2NEK0xPeE5mUWJtU3lvCk00YS8xeEFZWWhUUHhoOWdFQW9J
            eUFnUm02Q0V1YjdvQWNUOUxlT0hlUTQKLS0tIDY3UUM0K0RCYU0wRmFPNjhQd3ND
            VDBJMDRZekFuY1gxMmhmODVLeFBLRVEKcrW35Ja/F9Ti/YHkOODrKrcmytSGbpnE
            +9x07ZFbDokFmPddsbtcnuFvj0ttXShhEkntn9Hw74q+/jwcDUZOSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T13:35:18Z"
    mac: ENC[AES256_GCM,data:OuRQp1GmPG19hguVUEI11Y12np3L3QCrGqZdgVySIzfH69kG3bMvm8YSCm1TQh9m+S1CTG1Q01HN7naJ/XU3A+Er5lyWL/UlDS8faEbu0/PxyDwafaK1jG2JXe6hTykibRFg0Hkg4MPYFgt8w6t05YMlLV6vtc5WmjCdYihPk78=,iv:rkzULfiZZG51JVZO4rTz6x+kj/uhRJP/7loReU0Xo+I=,tag:kGiH0bPgVn15qQX2bdTIgw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
